# Generated by Django 4.1.13 on 2024-03-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="id_of_user",
            new_name="unique_id",
        ),
    ]
