# Generated by Django 4.1.13 on 2024-03-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_user_delete_todo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="user",
            new_name="CustomUser",
        ),
    ]
