# Generated by Django 4.1.13 on 2024-03-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("home", "0008_newuser_delete_submission"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="newUser",
            new_name="User",
        ),
    ]
