# Generated by Django 4.1.13 on 2024-03-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
