# Generated by Django 4.1.13 on 2024-03-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_user_custom_id_user_is_kgp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="custom_id",
            field=models.CharField(max_length=20),
        ),
    ]
