# Generated by Django 4.1.13 on 2024-03-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_user_custom_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="custom_id",
            field=models.CharField(default="XXXXXXXXXX", max_length=20),
        ),
    ]
