# Generated by Django 4.1.13 on 2024-03-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_user_custom_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="submission_link",
            field=models.TextField(default="null"),
        ),
        migrations.AlterField(
            model_name="user",
            name="custom_id",
            field=models.CharField(default="XXXXXXXXXX", max_length=20, unique=True),
        ),
    ]
